pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Hello Starting Job'
                 sh ''' ./merge_conflict.sh branch_list 
                '''
                
                
            }
        }
    }
}
