pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Hello Starting Job'
                sh '''  pwd
                '''
                
                
            }
        }
    }
}
